channels:
- conda-forge
dependencies:
- python=3.12.0
- pip<=26.0.1
- pip:
  - mlflow==3.9.0
  - cloudpickle==3.1.1
  - numpy==1.26.4
  - psutil==7.0.0
  - scikit-learn==1.5.1
  - scipy==1.14.1
name: mlflow-env
